### ISSUE TITLE
ArcadeFlow v14.4  I get a black screen

### ISSUE THREAD

**Issue by macsgv** [zpaolo11x/Arcadeflow#10]
Hello excellent work, after updating from version 13.9 to version 14.4 I only get a black screen.

I am using attractplus-2.6.2-attract-Windows.MXE-static-x86_64.7z

With version 13.9 everything works fine but with version 14.4 nothing works.

Any help in advance will be greatly appreciated.
Greetings.

********************************************

Attract-Mode Plus v2.6.2 (Windows, SFML 2.5.1 +7z +Curl)
avcodec 58.54.100 / avformat 58.29.100 / swscale 5.5.100 / avutil 56.31.100 / swresample 3.5.100

Config: D:\attract\attract.cfg

*** Initializing display: 'MAME'
 - Loaded master romlist 'MAME' in 29 ms (1369 entries kept, 0 discarded)
 - Constructed 35 filters in 7 ms (47915 comparisons)
Failed to load font "D:\attract\layouts/Arcadeflow/font_Roboto-Bold.ttf" (failed to create the font face)
 - AudioMode plugin: found 9 file(s) in: D:\attract\sounds

WARNING: some options in attract.cfg clash with Arcadeflow

Error loading font from file: D:\attract\layouts/Arcadeflow/font_Roboto-Bold.ttf

AN ERROR HAS OCCURED [the index 'redraw' does not exist]

CALLSTACK
*FUNCTION [main()] D:\attract\layouts/Arcadeflow/layout.nut line [7421]

LOCALS
[categorytable] TABLE
[regsys] TABLE
[data_surface] NULL
[nolist_blanker] NULL
[search] TABLE
[searchdata] NULL
[multifilterglyph] NULL
[mf] TABLE
[boxtitle] NULL
[logotitle] NULL
[all_scrape] TABLE
[all_meta_original] TABLE
[all_meta_edited] TABLE
[meta_original] TABLE
[meta_edited] TABLE
[metadata] TABLE
[yearnames] TABLE
[catnames_SS] TABLE
[catnames] TABLE
[focusindex] TABLE
[z_fields2] TABLE
[z_fields1] TABLE
[z_list] TABLE
[dispatchernum] 0
[dispatcher] ARRAY
[ratetonumber] TABLE
[keyboard_entrytext] ""
[key_selected] ARRAY
[key_sizes] ARRAY
[key_rows] ARRAY
[key_names] TABLE
[scroll] TABLE
[bgpicT] TABLE
[bgT] TABLE
[scrollersize] 19
[lettersize] TABLE
[fadevid] 9905
[delayvid] 9940
[vidstarter] 10000
[spdT] TABLE
[centercorr] TABLE
[deltacol] 2
[carrierT] TABLE
[pagejump] 10
[rotation] TABLE
[fl] TABLE
[scr] TABLE
[UI] TABLE
[gbrgb] TABLE
[colormapper] TABLE
[srfposhistory] ARRAY
[filtersw] ARRAY
[filterw] ARRAY
[impulse2] TABLE
[surfacePos] 0
[globalposnew] 0
[count] TABLE
[snd] TABLE
[satin] TABLE
[themeT] TABLE
[squarizer] false
[column] TABLE
[backs] TABLE
[search_base_rule] "Title"
[noshader] INSTANCE
[flowT] TABLE
[z_var] 0
[var] 0
[dat] TABLE
[bgs] TABLE
[bgvidsurf] NULL
[dir0] TABLE
[commandtable] TABLE
[system_data] TABLE
[orderdatalabel] TABLE
[huecycle] TABLE
[displaystore] 80
[SORTTABLE] TABLE
[DISPLAYTABLE] TABLE
[prfzero] TABLE
[z_info] TABLE
[transdata] ARRAY
[sorter] TABLE
[menucounter] 21
[multifilterz] TABLE
[umvisible] true
[umpresel] 0
[umtable] ARRAY
[selection_pre] NULL
[prf] TABLE
[DBGON] false
[z_af_collections] TABLE
[uifonts] TABLE
[zmenu] NULL
[gh] TABLE
[AF] TABLE
[IDX] ARRAY
[ap] """
[elapse] TABLE
[vargv] ARRAY
[this] TABLE
Script Error in D:\attract\layouts/Arcadeflow/layout.nut - the index 'redraw' does not exist
 - Loaded layout: D:\attract\layouts/Arcadeflow/ (layout.nut)
 - Constructed 1 filters in 0 ms (93 comparisons)
 - AudioMode plugin: found 9 file(s) in: D:\attract\sounds
 - Loaded layout: D:\attract\layouts/cosmo-mainmenu/ (layout.nut)

*** Initializing display: 'MAME'
 - Loaded master romlist 'MAME' in 29 ms (1369 entries kept, 0 discarded)
 - Constructed 35 filters in 8 ms (47915 comparisons)
Failed to load font "D:\attract\layouts/Arcadeflow/font_Roboto-Bold.ttf" (failed to create the font face)
 - AudioMode plugin: found 9 file(s) in: D:\attract\sounds

WARNING: some options in attract.cfg clash with Arcadeflow

Error loading font from file: D:\attract\layouts/Arcadeflow/font_Roboto-Bold.ttf

AN ERROR HAS OCCURED [the index 'redraw' does not exist]

CALLSTACK
*FUNCTION [main()] D:\attract\layouts/Arcadeflow/layout.nut line [7421]

LOCALS
[categorytable] TABLE
[regsys] TABLE
[data_surface] NULL
[nolist_blanker] NULL
[search] TABLE
[searchdata] NULL
[multifilterglyph] NULL
[mf] TABLE
[boxtitle] NULL
[logotitle] NULL
[all_scrape] TABLE
[all_meta_original] TABLE
[all_meta_edited] TABLE
[meta_original] TABLE
[meta_edited] TABLE
[metadata] TABLE
[yearnames] TABLE
[catnames_SS] TABLE
[catnames] TABLE
[focusindex] TABLE
[z_fields2] TABLE
[z_fields1] TABLE
[z_list] TABLE
[dispatchernum] 0
[dispatcher] ARRAY
[ratetonumber] TABLE
[keyboard_entrytext] ""
[key_selected] ARRAY
[key_sizes] ARRAY
[key_rows] ARRAY
[key_names] TABLE
[scroll] TABLE
[bgpicT] TABLE
[bgT] TABLE
[scrollersize] 19
[lettersize] TABLE
[fadevid] 9905
[delayvid] 9940
[vidstarter] 10000
[spdT] TABLE
[centercorr] TABLE
[deltacol] 2
[carrierT] TABLE
[pagejump] 10
[rotation] TABLE
[fl] TABLE
[scr] TABLE
[UI] TABLE
[gbrgb] TABLE
[colormapper] TABLE
[srfposhistory] ARRAY
[filtersw] ARRAY
[filterw] ARRAY
[impulse2] TABLE
[surfacePos] 0
[globalposnew] 0
[count] TABLE
[snd] TABLE
[satin] TABLE
[themeT] TABLE
[squarizer] false
[column] TABLE
[backs] TABLE
[search_base_rule] "Title"
[noshader] INSTANCE
[flowT] TABLE
[z_var] 0
[var] 0
[dat] TABLE
[bgs] TABLE
[bgvidsurf] NULL
[dir0] TABLE
[commandtable] TABLE
[system_data] TABLE
[orderdatalabel] TABLE
[huecycle] TABLE
[displaystore] 80
[SORTTABLE] TABLE
[DISPLAYTABLE] TABLE
[prfzero] TABLE
[z_info] TABLE
[transdata] ARRAY
[sorter] TABLE
[menucounter] 21
[multifilterz] TABLE
[umvisible] true
[umpresel] 0
[umtable] ARRAY
[selection_pre] NULL
[prf] TABLE
[DBGON] false
[z_af_collections] TABLE
[uifonts] TABLE
[zmenu] NULL
[gh] TABLE
[AF] TABLE
[IDX] ARRAY
[ap] """
[elapse] TABLE
[vargv] ARRAY
[this] TABLE
Script Error in D:\attract\layouts/Arcadeflow/layout.nut - the index 'redraw' does not exist
 - Loaded layout: D:\attract\layouts/Arcadeflow/ (layout.nut)
 ! Unexpectedly lost focus to: explorer.exe (31832)

**Comment by zpaolo11x** [comment]
The issue here is with the surface redraw feature, that is not implemented in Attract mode Plus release 2.6.2, but only in the stable master branch. You can get the most updated binaries from the Actions tab here:

https://github.com/oomek/attractplus/actions

and the latest master build is this:

https://github.com/oomek/attractplus/actions/runs/2985758087

scroll down to the artifacts section and download the archive for your system.

**Comment by macsgv** [comment]
Thank you very much the problem is solved and I think it's the best frontend I've tried.

Greetings and thanks for your time and prompt response.
