### ISSUE TITLE
ArcadeFlow 15.2 update failed

### ISSUE THREAD

**Issue by macsgv** [zpaolo11x/Arcadeflow#20]
Hi, the ArcadeFlow 15.2 Update fails, I have attached the log if you can help me. Thank you!

Attract-Mode Plus v2.6.2 (Build 163) (Windows, SFML 2.6.0 +7z +Curl)
avcodec 58.54.100 / avformat 58.29.100 / swscale 5.5.100 / avutil 56.31.100 / swresample 3.5.100

Config: D:\attract\attract.cfg

*** Initializing display: 'Commodore Amiga'
 - Loaded master romlist 'Commodore Amiga' in 13 ms (367 entries kept, 0 discarded)
 - Constructed 2 filters in 0 ms (734 comparisons)
 - AudioMode plugin: found 9 file(s) in: D:\attract\sounds

AN ERROR HAS OCCURED [the index 'mrgoemon' does not exist]

CALLSTACK
*FUNCTION [getallgamesdb()] D:\attract\layouts/Arcadeflow/layout.nut line [6772]
*FUNCTION [main()] D:\attract\layouts/Arcadeflow/layout.nut line [15583]

LOCALS
[fl] TABLE
[prf] TABLE
[uifonts] TABLE
[AF] TABLE
[z_list] TABLE
[metadata] TABLE
[@ITERATOR@] 1
[val] "1"
[item] "z_buttons"
[@ITERATOR@] 68
[gamemetas] TABLE
[gametable] "mrgoemon"
[@ITERATOR@] 26
[item] "Konami Classics.cfg"
[i] 25
[meta_edited] TABLE
[metadatapath] ""
[itemname] "Konami Classics"
[file] ""
[emulatordir] ARRAY
[emulatorpath] "D:\attract\emulators\"
[emulatorarray] ARRAY
[text_charsize] 139.2
[text_ratio] 0.6
[numchars] 12
[textobj] INSTANCE
[logopic] INSTANCE
[this] TABLE
[labelcounter] TABLE
[labelorder] ARRAY
[sortticks] TABLE
[sortticksarray] ARRAY
[sortlabels] TABLE
[sortlabelsarray] ARRAY
[fps] TABLE
[user_fg] NULL
[aflogoT] TABLE
[aflogo] INSTANCE
[attractitem] TABLE
[attract] TABLE
[zmenu_surface] INSTANCE
[shader_tx2] TABLE
[zmenu_sh] TABLE
[zmenu_surface_container] INSTANCE
[disp] TABLE
[disp0] TABLE
[hist_over] TABLE
[hist_screen] INSTANCE
[hist_screensurf] INSTANCE
[shadowshader] TABLE
[kerneldat] TABLE
[blursizeglow] TABLE
[hist_glow_shader] INSTANCE
[hist_glow_pic] INSTANCE
[shadowsurf_1] INSTANCE
[shadowsurf_2] INSTANCE
[shadowsurf_rt] INSTANCE
[shadow] TABLE
[histglow] TABLE
[gradshader] INSTANCE
[hist_text] TABLE
[hist_text_surf] INSTANCE
[shader_lcd] INSTANCE
[pixelpic] INSTANCE
[shader_lottes] INSTANCE
[LCDprf] TABLE
[CRTprf] TABLE
[hist_titletxt] INSTANCE
[hist_titletxt_bd] INSTANCE
[hist_titletxt_bot] INSTANCE
[hist_title_top] INSTANCE
[hist_title] INSTANCE
[hist_white] INSTANCE
[histgr] TABLE
[history_surface] INSTANCE
[hist_curr_rom] ""
[historypadding] 28
[shadowscale] 0.025
[hist_textT] TABLE
[hist_screenT] TABLE
[hist_titleT] TABLE
[hist] TABLE
[keyboard_text] INSTANCE
[kb] TABLE
[keyboard_surface] INSTANCE
[fb] TABLE
[prfmenu] TABLE
[overmenu] INSTANCE
[overmenuwidth] 554.4
[txtoalpha] INSTANCE
[bwtoalpha] INSTANCE
[gamed] TABLE
[blsize] TABLE
[letterobj] INSTANCE
[letterobjsurf] TABLE
[displayname] INSTANCE
[displaynamesurf] TABLE
[labelsurf] INSTANCE
[labelstrip] INSTANCE
[scroller2] INSTANCE
[scroller] INSTANCE
[scrollineglow] INSTANCE
[scrolline] INSTANCE
[separatorline] INSTANCE
[filternumbers] INSTANCE
[filterdata] INSTANCE
[data_surface_sh_1] INSTANCE
[data_surface_sh_2] INSTANCE
[data_surface_sh_rt] INSTANCE
[shader_tx] TABLE
[sh_scale] TABLE
[shaders] TABLE
[gradscaler] 1
[gradsizer] 8
[logo] TABLE
[greenshader] TABLE
[gr_vidsz] INSTANCE
[gr_snapz] INSTANCE
[gradsurf_1] INSTANCE
[gradsurf_rt] INSTANCE
[logosurf_rt] INSTANCE
[logosurf_1] INSTANCE
[txbox] INSTANCE
[txt2z] INSTANCE
[txt1z] INSTANCE
[txshz] INSTANCE
[loshz] INSTANCE
[snap_grad] ARRAY
[snap_glow] ARRAY
[surfacePosOffset] 1484
[tiles] TABLE
[vidbgfade] ARRAY
[vidposbg] 0
[corrector] 0
[vidindex] ARRAY
[vidpos] ARRAY
[aspectratioMorph] ARRAY
[gr_vidszTableFade] ARRAY
[tilesTableZoom] ARRAY
[tilesTableUpdate] ARRAY
[tilesTablePos] TABLE
[z_disp] ARRAY
[picture] TABLE
[shader_bg] TABLE
[bglay] TABLE
[mon2] TABLE
[shader_fr] TABLE
[flipshader] NULL
[frost] TABLE
[frostpic] TABLE
[overlay] TABLE
[tilez] ARRAY
[categorytable] TABLE
[regsys] TABLE
[data_surface] INSTANCE
[nolist_blanker] INSTANCE
[search] TABLE
[searchdata] INSTANCE
[multifilterglyph] INSTANCE
[mf] TABLE
[boxtitle] NULL
[logotitle] NULL
[all_scrape] TABLE
[all_meta_original] TABLE
[all_meta_edited] TABLE
[meta_original] TABLE
[meta_edited] TABLE
[metadata] TABLE
[yearnames] TABLE
[catnames_SS] TABLE
[catnames] TABLE
[focusindex] TABLE
[z_fields2] TABLE
[z_fields1] TABLE
[z_list] TABLE
[ratetonumber] TABLE
[keyboard_entrytext] ""
[key_selected] ARRAY
[key_sizes] ARRAY
[key_rows] ARRAY
[key_names] TABLE
[scroll] TABLE
[bgpicT] TABLE
[bgT] TABLE
[scrollersize] 19
[lettersize] TABLE
[fadevid] 9905
[delayvid] 9940
[vidstarter] 10000
[spdT] TABLE
[centercorr] TABLE
[deltacol] 2
[carrierT] TABLE
[pagejump] 10
[rotation] TABLE
[fl] TABLE
[scr] TABLE
[UI] TABLE
[gbrgb] TABLE
[colormapper] TABLE
[srfposhistory] ARRAY
[filtersw] ARRAY
[filterw] ARRAY
[impulse2] TABLE
[surfacePos] 0
[globalposnew] 0
[count] TABLE
[snd] TABLE
[satin] TABLE
[themeT] TABLE
[squarizertop] false
[squarizer] false
[column] TABLE
[backs] TABLE
[search_base_rule] "Title"
[noshader] INSTANCE
[flowT] TABLE
[z_var] 0
[var] 0
[dat] TABLE
[bgs] TABLE
[bgvidsurf] NULL
[dir0] TABLE
[commandtable] TABLE
[system_data] TABLE
[orderdatalabel] TABLE
[huecycle] TABLE
[displaystore] 12
[SORTTABLE] TABLE
[DISPLAYTABLE] TABLE
[prfzero] TABLE
[z_info] TABLE
[transdata] ARRAY
[sorter] TABLE
[menucounter] 22
[multifilterz] TABLE
[umvisible] true
[umpresel] 0
[umtable] ARRAY
[selection_pre] NULL
[prf] TABLE
[dispatchernum] 0
[dispatcher] ARRAY
[DBGON] false
[z_af_collections] TABLE
[uifonts] TABLE
[zmenu] TABLE
[gh] TABLE
[AF] TABLE
[IDX] ARRAY
[ap] """
[elapse] TABLE
[vargv] ARRAY
[this] TABLE
Script Error in D:\attract\layouts/Arcadeflow/layout.nut - the index 'mrgoemon' does not exist
 - Loaded layout: D:\attract\layouts/Arcadeflow/ (layout.nut)
 ! Unexpectedly lost focus to: explorer.exe (12840)

![image](https://user-images.githubusercontent.com/13799157/207614506-cc681b0e-0470-42a4-8592-ae870f00cfdf.png)

**Comment by macsgv** [comment]
The solution was to delete the metadata of a specific collection.

**Comment by zpaolo11x** [comment]
Sorry I completely missed this issue, yes there's a known bug in 15.2 regarding metadata, that is triggered when a game is in the metadata file but not in the actual romlist. There's a hotfix on the discord channel, and it will be fixed in 15.3.
